const ahora=new Date()
console.log(ahora)
const Fecha_prueba=new Date(2022,11,15)
console.log(Fecha_prueba)
const Dia_prueba=Fecha_prueba.getDate()
const mes_prueba=Fecha_prueba.getMonth()
const anio_prueba=Fecha_prueba.getFullYear()
console.log(Dia_prueba+"/",mes_prueba+"/",anio_prueba)